github/codeql-action

.github/pull_request_template.md, lib/upload-lib.js, lib/util.js, src/testdata/tool-names.sarif, src/upload-lib.ts, src/util.test.ts, src/util.ts
This pull request sends an array of all the tool names included in the sarif files to the upload endpoint.
=> Send tool names to upload endpoint

lib/finalize-db.js, src/finalize-db.ts
This PR improves the error message for custom queries that don't have a qlpack.yml or one that is invalid, and aborts the execution instead of continuing with analysis and upload.
Here is a workflow run with a missing qlpack: https://github.com/github/codeql-action/actions/runs/91020742
Here is a successful workflow run: https://github.com/github/codeql-action/actions/runs/91018560
=> Error on queries with missing/multiple languages

README.md, lib/config-utils.js, lib/finalize-db.js, src/config-utils.ts, src/finalize-db.ts
This PR adds an option for disabling the queries we run default.
A run without the `ignore-default-queries` set, it runs all the queries: https://github.com/github/codeql-action/runs/629305743?check_suite_focus=true
A run with `ignore-default-queries: false`, it runs all the queries: https://github.com/github/codeql-action/runs/629307092?check_suite_focus=true
A run with `ignore-default-queries: true` it only runs the custom queries: https://github.com/github/codeql-action/runs/629310667?check_suite_focus=true
=> Disable default queries

lib/upload-lib.js, src/upload-lib.ts
This should make the upload retry a few times and with a small amount of delay between attempts. Hopefully this will help get over very minor issues, though if there's a larger outage of github lasting more than a few seconds then it won't be able to help.
- I created branches to simulate various failure methods.
- `upload_retry` where everything is normal
- `upload_retry_error` where all attempts fail
- In the logs you can see the final error message and that it retries with the expected delays.
- `upload_retry_partial_error` where the first attempt fails
=> Add retrying to the upload

lib/upload-lib.js, src/upload-lib.ts
This pull request makes two changes designed to assist debugging the upload action. Firstly it increases the log level of the message listing which SARIF files are being uploaded, which is a very useful piece of information.
Secondly it fails the action if an attempt is made to upload a folder with no SARIF files in, since this is very likely to be a mistake.
- Successful upload here: https://github.com/Anthophila/chrisgavin/runs/636104360?check_suite_focus=true
- Failed upload here: https://github.com/Anthophila/chrisgavin/actions/runs/92977473
=> Improve feedback about what files are being uploaded in the upload-sarif Action.

lib/autobuild.js, src/autobuild.ts
This adds better messaging to tell the user what languages we aren't autobuilding and prompts them to replace this action with custom build steps if we do fail.
=> Improve errors & warnings in autobuild

README.md
=> Note in readme about go analysis in macos-latest

lib/external-queries.js, lib/util.js, src/external-queries.test.ts, src/external-queries.ts, src/util.ts
The external queries tests run in a fixed directory. This is arguably fine when run as part of CI, but if the tests are run multiple times locally then they start to interfere with each other.
To see it's working, you can see in the [test logs](https://github.com/github/codeql-action/runs/645786593)
```
Cloning into '/tmp/codeql-action-1XUxpg/github/codeql-go'
```
This PR creates a random tmp dir for each test run and deletes it when the test is done. I created a shared function for this because I intend to start using it for other tests as well.
Also by populating the `RUNNER_WORKSPACE` env var we can make it required in `checkoutExternalQueries` and this avoids the hardcoded alternative path.
@Daverlo
- Run test builds as necessary. Can be on this repository or elsewhere as needed in …
=> Use tmp dir for external queries test

.github/workflows/integration-testing.yml
Aborting the other jobs is unhelpful for determining if the issue is limited to only one operating system. Since the jobs are done mostly in parallel it shouldn't take significantly longer. This will make it use more actions minutes but at our level I think that is acceptable.
=> don't fail-fast on integration tests

lib/upload-lib.js, lib/util.js, src/upload-lib.ts, src/util.ts
Uploads the current ref in the status reports. We are including this in the final upload already, but we'd also like to have it in the status reports during execution.
Moved the calculation of the ref to a function so it'll be easier to change when we have to add support for pull requests.
@marcogario, @daverlo
=> upload ref in status report

.github/workflows/codeql.yml
Somehow I got this wrong in https://github.com/github/codeql-action/pull/48 and the checks (https://github.com/github/codeql-action/runs/726650976) didn't catch it because the codeql.yml workflow wasn't run for some reason and so didn't report an error.
=> Fix identation in workflow

README.md
This slims down the readme so we don't duplicate information that's already in the help docs so it'll be easier to keep it up to date. It does look a bit small now, but I'm not sure what else to put in it.
@jhutchings1 what are your thoughts?
=> Reduce duplication between help and readme

.github/update-release-branch.py, .github/workflows/update-release-branch.yml
Adds a script to create a PR once per week to update the `v1` release branch.
See https://github.com/Anthophila/robertbrignull-update-automation/pull/19 for an example of what it looks like.
We can also try running it on this repo before merging it. I've added a `repository_dispatch` trigger so it can be run on demand as well as on a schedule.
=> Add script to open PR for updating release branch

.github/update-release-branch.py
I made a mistake here as I thought `sorted` updated the list in-place, but that's not true. So the PRs in https://github.com/github/codeql-action/pull/71 weren't sorted as they were inteneded to have been.
I got suspicious as to why I was the conductor, when I think it should have been @alexkappa 
=> Fixing sorting of PRs

README.md
Setting `strategy: fail-fast` has no effect unless the workflow is run as part of a matrix build. It controls whether one matrix build failing causes other builds in that same matrix to be aborted. It has no effect within an individual run.
See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast for more info.
I'm removing this from the suggested usage example because it is unnecessary and misleading.
=> Remove `strategy: fail-fast`

.github/workflows/update-release-branch.yml
Adding this new event will allow us to trigger the workflow through the UI, instead of having to use the API.
Unfortunately we can't test it until it's on the default branch, but it seems to work. I did a test a t https://github.com/robertbrignull/workflow-test/actions?query=workflow%3Adispatch
@chrisgavin
=> Add workflow_dispatch event

.github/codeql/codeql-config.yml
I don't think we want to be analyzing the `lib` directory as that's all generated code and we're currently getting some duplicate alerts showing up.
It'll theoretically also show up alerts from dependencies, although I can't actually see any such alerts right now. Although this could be informative, it's not the way that codeql is meant to be used. It'll be more useful to rely on things like CVEs and dependabot to find out about vulnerabilities in dependencies.
=> Exclude lib directory from analysis

.vscode/launch.json, CONTRIBUTING.md
https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-vscode.md recommends passing the `debug` option to Ava.  However, in my experience Ava waits indefinitely when this option is used, without actually running any tests.
The increased timeout setting is so that tests won't fail prematurely because you're slowly stepping through code.
- **N/A** Confirm this change is backwards compatible with existing workflows.
=> Add support for debugging from VSCode

analyze/action.yml, queries/undeclared-action-input.ql
If this works the same as it did locally then this will fix all of the alerts from https://github.com/github/codeql-action/security/code-scanning
Some of them were false positives because our analysis was mistakenly determining that all of the methods from the CodeQL object were called, when actually they were just defined. I fixed this by giving the analysis knowledge of the CodeQL object and how it is defined. I'm a little worried the knowledge is too specific, so for example we'll have to adjust the query if we rename the method, but since it's all in one repository at least this would be easy to do. Resolving the codeql functions is then just done by name, which hopefully will be good enough. Again I think this is a case of make the analysis good enough and if it's a bit of an …
=> Fix undeclared action inputs

README.md
Fix the "Using a custom configuration" link the README. The actual ID of the header on the page is `#using-a-custom-configuration-file`, so I updated both the link and the link title to match. (as far as I can tell all other links in the README work as expected.)
---
As an aside (not sure where best to report this), the snippet for [Specifying directories to scan](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#specifying-directories-to-scan) in the docs seems to be outdated. `paths-ignore` and `paths` can no longer be specified in the `with:` statement, according to [this error message](https://github.com/ericcornelissen/svgo-action/runs/1097787080#step:3:1):
```
##[warning]Unexpected input(s) 'paths-ignore', valid …
```
=> Fix "Using a custom configuration" link in the README

analyze/action.yml
Hotfix to the `v1` branch.
The snippets are larger than expected in a few cases. This PR disables them by default so we have time to investigate further.
=> Disable snippets by default

.github/workflows/codeql.yml, .github/workflows/integration-testing.yml, .github/workflows/pr-checks.yml
See #182. Workflows are now triggered on all PRs but only on push on the main and v1 branch.
=> Reduce triggers in workflows

lib/defaults.json, src/defaults.json
=> Update default CodeQL version to codeql-bundle-20201008

python-setup/auto_install_packages.py, python-setup/tests/from_python_exe.py
Is now deprecated as described in https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
@Daverlo I don't know how this plays together with version compatibility, just spotted the warning on an action run, and thought I could fix it up.
=> Don't use ::set-env in python-setup

.github/workflows/python-deps.yml
The current Python CI jobs seem to assume the bundle will never be updated by referencing the bundle by exact version. They don't specify a static bundle to actually download though, so every time the bundle updates the CI will break.
I've fixed this by specifying the expected bundle as the one to download under the assumption that is what we want to test. We could also test the latest version, but that seems like it could break unexpectedly if there are changes to the Python extractor.
=> Fix Python CI jobs.

README.md
=> Change suggested workflow to analyse merge commit

python-setup/install_tools.sh
In the README of this repo, it's suggested to use the `ubuntu-latest` environment.
That environment will soon be upgraded to Ubuntu 20.04: https://github.com/actions/virtual-environments/issues/1816
As pointed out in that issue, the updated image comes without a Python 2 pip preinstalled:
Setup Python dependencies
/home/runner/work/_actions/github/codeql-action/v1/python-setup/install_tools.sh
[...]
+ python2 -m pip install --user --upgrade pip setuptools wheel
/usr/bin/python2: No module named pip
Warning: Unable to download and extract the tools needed for installing the python dependecies. You can call this action with 'setup-python-dependencies: false' to disable this process.
=> Make sure a Python 2 pip is installed

.github/workflows/codeql.yml
We can only analyze PRs against those branches we are analyzing on push.
=> Only analyze PRs against main and v1

.github/workflows/check-expected-release-files.yml
This adds a check to make sure all the expected files on the CodeQL bundle release exist, including the runner and the CodeQL complete bundle, neither of which are covered by other checks.
(Adding this because I initially forgot to rename the `codeql-bundle-all.zip` file to `codeql-bundle.zip`.)
=> Add a check to ensure expected CodeQL release files exist.

python-setup/install_tools.sh
It seems like in some cases this script gets analyzed. We can either remove it after running it, or just not save it at all.
=> Prevent accidental analysis of the `get-pip.py` script.

python-setup/install_tools.sh
This is a cherry-pick of #349 onto `v1`.
=> Prevent accidental analysis of the `get-pip.py` script. [v1 cherry-pick]

upload-sarif/action.yml
👋🏻 I'm proposing this change alongside some similar changes to the documentation. We want to make sure that people are aware of the limit on the number of results that will be processed per SARIF file. This is rarely a problem for results generated by CodeQL but a few people have encountered it when running 3rd party tools that may be "noisy".
=> Update description to include limit on number of results

.github/workflows/pr-checks.yml
We're getting a lot of "Could not read workflow" errors on the pr-checks because they move the repository files out of the way in order to move some test files back in. We can avoid the error by making sure we don't move the workflow file that's executing, or at least we move it back to where it was.
=> Move .github/workflows back where it was

.github/update-release-branch.py
I think we actually want a one-way comparison here, rather than two-way. With the current two-way comparison, cherry-picks like #350 are reported as being included in every merge.
=> Use an asymmetric Git log when updating the release branch.

.github/workflows/pr-checks.yml
This will need to be fixed properly before 1.17 when `GO111MODULE` will be ignored.
=> Check if this mitigates the go 1.16 issue

CONTRIBUTING.md
=> Fix information about `npm ci`

.github/workflows/update-supported-enterprise-server-versions.yml
Don't run the cron workflow on forks, since they lack the necessary secrets.
=> Actions: Run enterprise versions workflow only on the parent repo

.github/update-release-branch.py, .github/workflows/post-release-mergeback.yml, CHANGELOG.md, package-lock.json, package.json, runner/package-lock.json, runner/package.json
And manually mergeback v1 into main.
Needed to do a few fixes here:
- Fix the logic in `post-release-mergeback.yml` workflow
- Unshallow before pushing a tag
- Fix the `version` script so that newlines are correctly stripped to keep `removeNPMAbsolutePaths` happy
- Manually updated the changelog.
=> Fix the mergeback workflow

queries/unguarded-action-lib.ql
I'm not 100% sure this change is correct but the PR checks should tell us as this should introduce at least one alert because it'll now spot accesses of `actions-util.ts`. Because it's using `matches` but then with a string with no wildcards in it I'm assuming this must be a mistake.
Alternatively we could probably just use `getImportedPath().getValue() = "./actions-util")` since we currently have all our source in one directory. Is that better? Using `matches` lets us catch this potential future edge case.
=> Update unguarded-action-lib.ql to catch uses of actions-util.ts

.github/workflows/post-release-mergeback.yml
gh will complain if there is an empty `""`, which is the case if
`$DRAFT` is unset.
=> Remove quotes around `$DRAFT` argument

.github/update-release-branch.py, .github/workflows/pr-checks.yml, tests/multi-language-repo/.github/codeql/codeql-config-packaging.yml
This change ensures that the the script can handle
commits with no committer in them. This will happen
for some commits that are auto-generated during
PRs.
=> Fix update-release-branch-fix.py

.github/update-release-branch.py, .github/workflows/post-release-mergeback.yml, CHANGELOG.md
The changelog for an empty version will now be:
```
No user facing changes.
```
And this will appear in the final changelog when there is an actual release.
The benefits are that users will see regular release cycles and know
how old versions are even if there's no changes for a particular version
If we find that we are going months without any user facing changes, but
we have non-visible changes, then we can rethink this strategy.
But I think this is nicer than having empty sections for a version.
Fixes #579.
=> Update changelog template

.github/workflows/pr-checks.yml
This PR changes the integration tests of the CodeQL Action to also run against a recent nightly build of the CodeQL bundle. This should help catch compatibility issues arising from changes in the Action earlier.
=> Run tests against nightly CLI bundles

.github/workflows/pr-checks.yml
=> Remove a TODO and use defautl tools option

.github/depandabot.yml, .github/workflows/pr-checks.yml, .github/workflows/script/check-node-modules.sh, .github/workflows/update-dependencies.yml, node_modules/.package-lock.json, package-lock.json
Closes https://github.com/github/codeql-coreql-team/issues/1344
This adds a new workflow (triggered by a label) that updates the checked-in dependencies on a PR branch. It also enables Dependabot and has it apply the relevant label to have the checked-in dependencies updated. Unfortunately, the workflow will not work on forks due to missing the permissions to push to other user's forks, so we can't use it on our own PRs. It should work on Dependabot's PRs, though, since it creates its PRs from the main repo.
=> Enable dependabot automatic updates

.github/workflows/post-release-mergeback.yml
The first mergeback workflow after https://github.com/github/codeql-action/pull/630 failed (https://github.com/github/codeql-action/pull/634) because the lockfile did not have the new version ([this commit](https://github.com/github/codeql-action/pull/634/commits/fb190722374162e20bbea5ef72a467e66d531efe) fixed it after I manually added the label). Adding the label on the PR should make sure that commit gets made automatically.
=> Update lockfile in mergeback

runner/package-lock.json, runner/package.json
The dependencies we use when building the runner can't be automatically updated by Dependabot since they are in a `package.json` in a sub-folder rather than in the main one. Nonetheless, we should still occasionally update them. In particular, there is currently an alert on one of the transitive dependencies being affected by this CVE (https://github.com/advisories/GHSA-ww39-953v-wcq6), which I believe will be resolved by this update.
=> Update runner building dependencies

.github/dependabot.yml
This PR enables Dependabot on the dependencies for building the CodeQL runner, which have their own `package.json` and `package-lock.json` in a subfolder. Note we don't need the new "Update dependencies" label for these PRs as the dependencies there are not checked in.
=> Enable Dependabot on runner

.github/update-release-branch.py, .github/workflows/check-expected-release-files.yml, .github/workflows/codeql.yml, .github/workflows/post-release-mergeback.yml, .github/workflows/pr-checks.yml, .github/workflows/python-deps.yml, .github/workflows/update-dependencies.yml, .github/workflows/update-release-branch.yml
PR checks aren't triggered on PRs created by Actions workflows.  This change marks PRs created by workflows as draft to prompt maintainers to take the PR out of draft, thereby triggering PR checks.
Update release branch workflow:
- Test workflow run: https://github.com/github/codeql-action/actions/runs/1095021129
- Test PR: https://github.com/github/codeql-action/pull/680
Post-release mergeback workflow:
- Test workflow run: https://github.com/github/codeql-action/actions/runs/1095020479
- Test PR: https://github.com/github/codeql-action/pull/681
=> Create PRs as drafts to prompt maintainers to trigger PR checks

.github/workflows/pr-checks.yml
Add a separate job that analyses the multilanguage test repo's Ruby code.
For now, run this only with the latest released build of CodeQL pointed to in `defaults.json`.
The nightly build and the cached builds don't support Ruby yet.
In future, we can update this and other PR checks to test a wider range of cases.
=> Add PR check job for Ruby beta

node_modules/.package-lock.json, node_modules/jsonschema/README.md, node_modules/jsonschema/lib/attribute.js, node_modules/jsonschema/lib/helpers.js, node_modules/jsonschema/lib/index.d.ts, node_modules/jsonschema/lib/index.js, node_modules/jsonschema/lib/scan.js, node_modules/jsonschema/lib/validator.js, node_modules/jsonschema/package.json, package-lock.json, package.json
Reverts github/codeql-action#650
`jsonschema` 1.3.0 starts validating `uri-reference` JSON fields, which exposes a CodeQL CLI bug where [artifact location URI in SARIF output lacks necessary percent encoding](https://github.com/github/codeql-coreql-team/issues/1400).  This revert temporarily mitigates the SARIF upload breakage until the future release of CodeQL CLI 2.6.0 propagates to CodeQL analysis actions.
=> Revert "Bump jsonschema from 1.2.6 to 1.4.0"

.github/workflows/codeql.yml, CHANGELOG.md, README.md
And adds a permissions block to the README.
Fixes #464.
=>  Updates the permissions block to be minimal

.github/workflows/pr-checks.yml
If we're running on push, then we can reintroduce the logic that skips running with `tools: latest` when it would be the same as running with `tools: null`.
=> Reduce the number of PR checks that are run on `push`

.github/workflows/pr-checks.yml, tests/multi-language-repo/.github/codeql/codeql-config-packaging.yml
=> Update integration test pack versions

lib/defaults.json, src/defaults.json
Bumps the default version to `codeql-bundle-20210909` which contains a patch to an upgrade script. This shouldn't actually affect the Action but it will be useful to run this repo's CI checks on the new bundle.
=> Bump release to `codeql-bundle-20210909`

.github/dependabot.yml
This PR changes our Dependabot configuration to ignore minor and patch releases of dependencies and only try to carry out an update when the major version is bumped. Per the [documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore), this will not affect security updates which will still be carried out immediately.
=> Dependabot: Ignore minor and patch versions

.github/dependabot.yml
This commit addresses the error:
```
The property '#/updates/0/ignore' of type object did not match the following type: array
The property '#/updates/1/ignore' of type object did not match the following type: array
```
=> Fix dependabot ignore syntax

.github/workflows/pr-checks.yml, CHANGELOG.md, lib/defaults.json, src/defaults.json, tests/multi-language-repo/build.sh
Part of the 2.6.2 release process.
=> Bump default CodeQL version to 2.6.2 bundle

.github/workflows/update-dependencies.yml
This addition in https://github.com/github/codeql-action/pull/786 appears to have broken the workflow, reverting for now.
Successful run without that: https://github.com/github/codeql-action/actions/runs/1396501976/workflow
Failing run with that: https://github.com/github/codeql-action/actions/runs/1421162875/workflow
=> Remove `persist-credentials: false` from workflow

CHANGELOG.md, lib/defaults.json, src/defaults.json
Bumps the default version of the CodeQL bundle to 2.7.2.
=> Bump default CodeQL version to 2.7.2

.github/workflows/__debug-artifacts.yml, .github/workflows/__go-custom-queries.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/__packaging-config-inputs-js.yml, .github/workflows/__packaging-config-js.yml, .github/workflows/__packaging-inputs-js.yml, .github/workflows/__remote-config.yml, .github/workflows/__split-workflow.yml, .github/workflows/__test-local-codeql.yml, .github/workflows/__unset-environment.yml, .github/workflows/pr-checks.yml, pr-checks/checks/debug-artifacts.yml, pr-checks/checks/go-custom-queries.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/checks/packaging-config-inputs-js.yml, pr-checks/checks/packaging-config-js.yml, pr-checks/checks/packaging-inputs-js.yml, pr-checks/checks/remote-config.yml, pr-checks/checks/split-workflow.yml, pr-checks/checks/test-local-codeql.yml, pr-checks/checks/unset-environment.yml
A few CI checks are currently failing because dotnet is waiting for some user-input. e.g. https://github.com/github/codeql-action/runs/4381100962?check_suite_focus=true
This seems to be because of a change in the CodeQL CLI and how it handles dotnet under tracing in macos. This may get fixed in CodeQL but for now a workaround to get our CI working is to call `dotnet restore` when not traced by CodeQL so it can do it's first-time setup without interference.
=> Deal with new dotnet version

.github/workflows/__debug-artifacts.yml, .github/workflows/__go-custom-queries.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/__packaging-config-inputs-js.yml, .github/workflows/__packaging-config-js.yml, .github/workflows/__packaging-inputs-js.yml, .github/workflows/__remote-config.yml, .github/workflows/__split-workflow.yml, .github/workflows/__test-local-codeql.yml, .github/workflows/__unset-environment.yml, .github/workflows/pr-checks.yml, pr-checks/checks/debug-artifacts.yml, pr-checks/checks/go-custom-queries.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/checks/packaging-config-inputs-js.yml, pr-checks/checks/packaging-config-js.yml, pr-checks/checks/packaging-inputs-js.yml, pr-checks/checks/remote-config.yml, pr-checks/checks/split-workflow.yml, pr-checks/checks/test-local-codeql.yml, pr-checks/checks/unset-environment.yml
Now that the underlying tracing issue that caused us to need these has been fixed, I believe our CI should pass without them.
cc. @robertbrignull
=> Remove `dotnet restore` calls from CI checks

CHANGELOG.md
Looks like the changelog entry in https://github.com/github/codeql-action/pull/843 was in the section for an already released version. This is moving it into the right place.
=> Move changelog entry into correct place

python-setup/install_tools.ps1, python-setup/install_tools.sh
Force the virtualenv version to be 20.11 or less. The 20.12 version is failing for python 2 right now.
=> Force virtualenv version

.github/prepare-test/action.yml
Looks like I accidentally committed some debugging output when I wrote this part of our CI. This PR removes it.
=> Remove debugging output

CHANGELOG.md, analyze/action.yml, upload-sarif/action.yml
This reverts commit b661ef1697d555e1f2ab5c42d3c60b5bb71b6cf2.
It looks like this change caused issues with analyses on pull requests from forks. This is due to the complicated nature of the permissions of workflows run on these pull requests. They are able to upload analyses for their own pull requests refs, but are not able to access other Code Scanning APIs such as the one required to get the status of a delivery.
This reverts adding this new functionality until we update the API to make it able to safely determine whether a pull request should be able to get the status of a particular delivery.
This is a hotfix on the v1 branch.
=> Revert "Start waiting for processing by default."

.github/workflows/__analyze-ref-input.yml, .github/workflows/__go-custom-queries.yml, .github/workflows/__go-custom-tracing.yml, .github/workflows/__remote-config.yml, .github/workflows/__upload-ref-sha-input.yml, .github/workflows/pr-checks.yml, .github/workflows/python-deps.yml, pr-checks/checks/analyze-ref-input.yml, pr-checks/checks/go-custom-queries.yml, pr-checks/checks/go-custom-tracing.yml, pr-checks/checks/remote-config.yml, pr-checks/checks/upload-ref-sha-input.yml
`windows-latest` is currently migrating from an image based on Windows Server 2019 to an image based on Windows Server 2022.  This breaks some of our CI jobs for two reasons:
1. Build tracing doesn't yet support Windows Server 2022
2. Python 2 isn't supported in the `windows-2022` image.
This PR addresses (1) by moving relevant jobs to use the `windows-2019` image and (2) by fixing a typo that prevented `setup-python` from downloading and installing Python 2 when it's not already in the Actions VM image.
=> Fix CI jobs that broke as a result of `windows-latest` being upgraded to Windows Server 2022

CHANGELOG.md, README.md
This PR updates the changelog and README with information about compatibility with the `windows-latest` virtual environment, which is transitioning to Windows Server 2022.
=> Update changelog and README with build tracing compatibility info

.github/workflows/update-supported-enterprise-server-versions.yml
Actions will not run checks on PRs opened by Actions, so opening the PR as draft allows us to trigger PR checks by marking the PR as ready for review.
The `draft` input appears in the version of the Action that we've pinned: see [this part of the README](https://github.com/peter-evans/create-pull-request/tree/c7f493a8000b8aeb17a1332e326ba76b57cb83eb#action-inputs).
=> Open "Update supported enterprise versions" PR as draft

.github/workflows/__analyze-ref-input.yml, .github/workflows/__debug-artifacts.yml, .github/workflows/__extractor-ram-threads.yml, .github/workflows/__go-custom-queries.yml, .github/workflows/__go-custom-tracing-autobuild.yml, .github/workflows/__go-custom-tracing.yml, .github/workflows/__javascript-source-root.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/__packaging-config-inputs-js.yml, .github/workflows/__packaging-config-js.yml, .github/workflows/__packaging-inputs-js.yml, .github/workflows/__remote-config.yml, .github/workflows/__rubocop-multi-language.yml, .github/workflows/__split-workflow.yml, .github/workflows/__test-local-codeql.yml, .github/workflows/__test-proxy.yml, .github/workflows/__test-ruby.yml, .github/workflows/__unset-environment.yml, .github/workflows/__upload-ref-sha-input.yml, pr-checks/checks/analyze-ref-input.yml, pr-checks/checks/go-custom-queries.yml, pr-checks/checks/go-custom-tracing.yml, pr-checks/checks/remote-config.yml, pr-checks/checks/upload-ref-sha-input.yml, pr-checks/sync.py
Expands our test coverage to test against `windows-2022`. In particular, we run these tests in addition to existing ones whenever a test is with a new CLI version and was already being run on Windows.
=> Expand PR checks to cover `windows-2022`

.github/workflows/__analyze-ref-input.yml, .github/workflows/__debug-artifacts.yml, .github/workflows/__extractor-ram-threads.yml, .github/workflows/__go-custom-queries.yml, .github/workflows/__go-custom-tracing-autobuild.yml, .github/workflows/__go-custom-tracing.yml, .github/workflows/__javascript-source-root.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/__packaging-config-inputs-js.yml, .github/workflows/__packaging-config-js.yml, .github/workflows/__packaging-inputs-js.yml, .github/workflows/__remote-config.yml, .github/workflows/__rubocop-multi-language.yml, .github/workflows/__split-workflow.yml, .github/workflows/__test-local-codeql.yml, .github/workflows/__test-proxy.yml, .github/workflows/__test-ruby.yml, .github/workflows/__unset-environment.yml, .github/workflows/__upload-ref-sha-input.yml, .github/workflows/pr-checks.yml, .github/workflows/python-deps.yml, .github/workflows/release-runner.yml, .github/workflows/split.yml, .github/workflows/update-dependencies.yml, .github/workflows/update-release-branch.yml, .github/workflows/update-supported-enterprise-server-versions.yml, pr-checks/sync.py
For most CI jobs. Based on some eye-balling 30 minutes should be enough time for all jobs to complete.
- [n/a] Confirm this change is backwards compatible with existing workflows.
- [n/a] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [n/a] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.
=> Add a timeout of 30 min

lib/config-utils.test.js, lib/util.js, src/config-utils.test.ts, src/util.ts
Bumps the version range of the ML-powered query pack we run on `security-extended` and `security-and-quality` to the next minor version, i.e. `~0.1.0`.  Here are some of the changes we're shipping:
- Query help improvements
- Queries now have CWE tags
- Optimizations to improve query runtime
- (Internal) The ATM model is now shipped within its own pack
=> Bump ML-powered queries to v0.1.0

.github/workflows/check-expected-release-files.yml, CHANGELOG.md
The runner is now deprecated and won't be included in future releases 🎉
Let's remove it from the expected files in our releases so the CI checks on them can pass.
=> Remove runner from expected release files

CHANGELOG.md, lib/defaults.json, src/defaults.json
Part of the 2.8.4 release process.
=> Bump default CodeQL version to 2.8.4

.github/workflows/update-release-branch.yml
The underlying Python script expects arguments of the form `v2-release` rather than `release-v2`.
=> Fix typos in release workflow

.github/workflows/pr-checks.yml
Cherry-picks https://github.com/github/codeql-action/commit/9da34a6ec642856a41b22a13739d75e3c505d85c, which we already have on the `v1` branch (where it is needed to avoid a failure) onto `main`. I think we should do this so that our PR checks are the same on all the branches, even though we don't _need_ it outside of `v1`.
=> Avoid failure if `@types/node` is already 12.12

.github/workflows/__ml-powered-queries.yml, pr-checks/checks/ml-powered-queries.yml, tests/ml-powered-queries-repo/add-note.js, tests/ml-powered-queries-repo/app.js, tests/ml-powered-queries-repo/index.js, tests/ml-powered-queries-repo/logger.js, tests/ml-powered-queries-repo/models/note.js, tests/ml-powered-queries-repo/models/user.js, tests/ml-powered-queries-repo/notes-api.js, tests/ml-powered-queries-repo/read-notes.js, tests/ml-powered-queries-repo/users-api.js
Based on #1010.
This PR adds a check to ensure that ML-powered queries are run correctly:
- On Linux and macOS, validate that:
- The four ML-powered queries appear in the `rules` of the SARIF output
- At least one of these queries generates an alert with a score on a test database
- On Windows, validate that:
- None of the four ML-powered queries appear in the `rules` of the SARIF output
- No alerts are generated by ML-powered queries on a test database (admittedly this is a little redundant with the prior check)
Example run: https://github.com/github/codeql-action/actions/runs/2066597691
We should add these jobs to the branch protection rules immediately before merging this PR.
=> Add a PR check to validate that ML-powered queries are run correctly

python-setup/auto_install_packages.py
As previously written, if codeql finds a `Pipfile`, but no `Pipfile.lock`, it will run `pipenv install` with args that require `Pipfile.lock` to exist. Pipfile will fail with this message:
```
Usage: python -m pipenv install [OPTIONS] [PACKAGES]...
ERROR:: Pipfile.lock must exist to use --keep-outdated!
package installation with pipenv failed, see error above
```
This changeset enables auto_install to work with Pipfile when there is no lock. (Bonus: `--skip-lock` is generally a bit faster.)
=> Support Pipfile without Pipfile.lock

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Bump default CodeQL version to 2.9.0

README.md
git.io is deprecated, so use the full link to docs.github.com instead.
- [N/A] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.
=> README: Replace git.io shortlink with full link

.github/workflows/update-required-checks.yml, CONTRIBUTING.md
Update contributing guide. Ensure this workflow runs once a week.
=> Add workflow to regenerate required checks

.github/workflows/update-required-checks.yml
I needed to do a few things in order to get the update-required-checks workflow to succeed:
1. Create a new secret for the codeql-ci user
2. Add this secret to this repository
3. Add the codeql-ci user as an admin for this repository
Successful run:
https://github.com/github/codeql-action/actions/runs/2259813401
Note that this run removed all previous checks. I'll add them back manually.
=> Add permissions to workflow

.github/update-release-branch.py
We only need to run `git commit` after the `git merge` call if there were conflicts.
=> Remove an extraneous commit during the release process

README.md
As of December 2021, we do not return missing **base** analysis anymore. Instead on the PR that introduces code scanning, we will report all alerts as new.
We can still report a missing **after**, especially when we deal with outdated configurations, but that should happen significantly less often (and was also not originally explained in this paragraph).
=> Remove outdated guidance on missing analysis

.github/workflows/expected-queries-runs.yml, .github/workflows/query-filters.yml, .github/workflows/script/update-required-checks.sh
This breaks the API. Also, fix the checks that had duplicate names.
=> Ensure there are no duplicates when sending up required checks

.github/workflows/script/update-required-checks.sh
This script didn't quite work on my machine because the update check that we want to filter out was called `update` and `jq` was matching in a case-sensitive way so did not filter it out with `contains("Update")`. Lets add another case to the filter to cover this, to avoid others hitting this issue.
=> Fix issue with required checks sync script

runner/package-lock.json, runner/package.json
Note that this changes the lock file format from 1 to 2, so there are many changes here.
This PR is the result of runner `npm audit fix` in the runner directory. Since the runner is deprecated I am not too concerned one way or the other about these dependabot warnings. I do want our project to look clean, though.
=> Fix dependabot warnings in runner

.github/workflows/python-deps.yml, CHANGELOG.md
Fixes https://github.com/github/codeql-action/issues/1122
=> Disable python2 + poetry

.github/workflows/python-deps.yml
No need to run this workflow on all PRs, only those that change the Python dependency installation mechanism.
Reviewer note: This will need an update to the branch protection rules, because these checks can no longer be required on all PRs.
- [N/A] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [N/A] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.
=> CI: Add path filters to python-deps workflow

.github/workflows/pr-checks.yml
Reduce the number of concurrent jobs (by 1, but every job counts!).
This will require a branch protection rule update, renaming `check-js` to `Check JS` and removing `Lint`.
- [N/A] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [N/A] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.
=> CI: Combine JS lint and JS check jobs

init/action.yml
This is a no-op for now, but let's add it in so DCA can opt out already without any warnings.
=> Add option to override TRAP caching feature flag

.github/workflows/python-deps.yml, CHANGELOG.md
Just like we did for poetry and Python 2 in https://github.com/github/codeql-action/pull/1124
From looking at changelogs, Python2 has not been supported in Pipenv since [v2021.11.5](https://pipenv.pypa.io/en/latest/changelog/#id149)
It has started failing CI checks: https://github.com/github/codeql-action/runs/7830121042?check_suite_focus=true
=> Disable python2 + pipenv tests

node_modules/.package-lock.json, package-lock.json, package.json
Complement to https://github.com/github/codeql-action/pull/1197.  This fixes the version number on the `releases/v1` branch, which should be 1.1.19 instead of 2.1.19.  The bug that got us into this position is explained on and fixed by the linked PR.
=> Update version number to 1.1.19

CHANGELOG.md, lib/defaults.json, src/defaults.json
Update the default CodeQL bundle to [codeql-bundle-20220908](https://github.com/github/codeql-action/releases/tag/codeql-bundle-20220908).
=> Bump CodeQL version to 2.10.5

CHANGELOG.md
Adds a CHANGELOG for TRAP caching to the next release, as we will soon begin rolling this out to external users.
=> Add CHANGELOG note for TRAP caching

.github/update-release-branch.py, .github/workflows/post-release-mergeback.yml
- Recommend removing and then re-adding the "Update dependencies" label when appropriate to avoid having to run the full set of PR checks twice.  This isn't a completely satisfying solution but should reduce friction before we implement something that updates the dependencies without requiring an additional triggering step.
- Recommend marking the PR as ready for review to avoid having to close and reopen the PR to run checks.
- Avoid duplicating the PR titles like this:
Instead, just link the PR and let GitHub format the title nicely.
=> Improve the descriptions of PRs created by the release process

python-setup/install_tools.ps1, python-setup/install_tools.sh
Context for previous version is
https://github.com/github/codeql-action/pull/862
Locally, I was able to install `20.15.1` with Python2.
I don't see any reason why python3 version should be restricted.
=> python-setup: Allow newest `virtualenv`

CHANGELOG.md, python-setup/auto_install_packages.py, python-setup/install_tools.ps1, python-setup/install_tools.sh
Fixes https://github.com/github/codeql-action/issues/1241
=> python-setup: Add support for Poetry 1.2

.github/workflows/python-deps.yml, python-setup/auto_install_packages.py, python-setup/install_tools.ps1, python-setup/install_tools.sh
Fixes https://github.com/github/codeql-action/issues/1249
As described [here](https://askubuntu.com/questions/1406304/virtualenv-installs-envs-into-local-bin-instead-of-bin), when using Ubuntu 22.04 with new enough versions of `setuptools` (60.0.0+), the virtual environment created with `virtualenv` will put binaries in `<venv-path>/local/bin` instead of `<venv-path>/bin`.
Next release after `20.16.5` of `virtualenv` will include a fix for this ([PR](https://github.com/pypa/virtualenv/pull/2415)).
=> python-setup: Fix venv creation in Ubuntu 22.04

lib/actions-util.js, src/actions-util.ts
=> Correct program name

.github/workflows/__go-custom-queries.yml, pr-checks/checks/go-custom-queries.yml
Previously, we considered `go` a non-traced language, and so the tracer was not imported to this workflow at all. Now that we are considering it traced, we need to add this additional environment variable, which is required for our MacOS tests to not time out waiting for a GUI popup. 
We already do this in several other Go-specific checks, such as https://github.com/github/codeql-action/blob/main/.github/workflows/__go-custom-tracing-autobuild.yml and https://github.com/github/codeql-action/blob/main/.github/workflows/__go-reconciled-tracing-autobuilder.yml
=> Add dotnet env variable to workflow

.github/workflows/debug-artifacts-failure.yml
The new Go extraction reconciliation feature flag treats Go as a traced rather than scanned language, and so it does not run `database trace-command` and produce logs from this command. The Go extractor and autobuilder themselves also do not create log files; their logs are written to stdout. Therefore, our check for the log artifact upon failure should be removed in this case only.
We continue to check for Go logs when debug artifacts succeed in https://github.com/github/codeql-action/actions/workflows/debug-artifacts.yml because we should then see other logs from database finalization.
=> Stop checking for Go log artifacts on failure

CHANGELOG.md
=> Add changelog note for Go extraction reconciliation

.github/update-release-branch.py, .github/workflows/post-release-mergeback.yml
We want to add an explicit statement that merging release commits should not be squashed or rebased 😸
=> Clarify merging with merge commit

lib/feature-flags.js, src/feature-flags.ts
2.11.1 has a fix in it for parsing query filters. Workflows using query filters will break if they are using syntax like:
```yaml
- exclude:
id: foo/bar
```
instead of
```yaml
- exclude:
- id: foo/bar
```
So, prevent users of CLI versions earlier than 2.11.1 from using the cli config parsing flag.
=> Bump the min version for code scanning config in the cli

.github/workflows/post-release-mergeback.yml
Previously the quoted values weren't visible in the PR description. See https://github.com/github/codeql-action/pull/1324 for an example.
=> Fix mergeback PR description

.github/workflows/__test-proxy.yml, pr-checks/checks/test-proxy.yml
`datadog/squid` no longer exists, so replace it with `ubuntu/squid`.  Also bump the Ubuntu version while we're here.
=> Fix missing Docker image in proxy test

README.md
This change adds Go to the list of compiled languages that may be autobuilt, or manually built, in our documentation.
A PR to add it to the official starter workflow is up at https://github.com/actions/starter-workflows/pull/1796 as well.
=> Add Go to list of supported languages

.github/workflows/__export-file-baseline-information.yml, .github/workflows/__ml-powered-queries.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/__ruby.yml, .github/workflows/__swift-autobuild.yml, .github/workflows/__swift-custom-build.yml, pr-checks/checks/export-file-baseline-information.yml, pr-checks/checks/ml-powered-queries.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/checks/ruby.yml, pr-checks/checks/swift-autobuild.yml, pr-checks/checks/swift-custom-build.yml
The version installed in the latest runner image, 5.7.1, is not yet supported.
cc @AlexDenisov
=> Use Swift version 5.7 in PR checks

CHANGELOG.md, lib/defaults.json, src/defaults.json
For some reason `npm run build` wasn't updating lib so I did it manually.
=> Update default CodeQL bundle version to 2.11.4

python-setup/install_tools.ps1, python-setup/install_tools.sh
Removes the hotfix from https://github.com/github/codeql-action/pull/1257
Have not updated either, since this should not be a user visible change
=> python-setup: rely on new `virtualenv` for venv creation in Ubuntu 22.04

.github/workflows/script/update-required-checks.sh
=> update-required-checks.sh: fix argument handling

.github/setup-swift/action.yml, .github/workflows/__export-file-baseline-information.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/__swift-autobuild.yml, .github/workflows/__swift-custom-build.yml, pr-checks/checks/export-file-baseline-information.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/checks/swift-autobuild.yml, pr-checks/checks/swift-custom-build.yml
This PR changes the `setup-swift` Action to set up the version of Swift the extractor declares (except on Windows). It also adds the `nightly-latest` PR check back to a couple of PR checks, which were removed in https://github.com/github/codeql-action/pull/1412 to unblock the release.
Note that after this PR merges, we should remember to update the corresponding integration test within the CLI, and include the bumped `setup-swift` SHA (https://github.com/github/codeql-action/pull/1415) as well. 
When the newest version of the CLI (that supports 5.7.1) makes it to `latest` and `cached`, we should be able to remove this logic and unconditionally setup 5.7.1, as future versions of the extractor should maintain backwards compatibility with prior Swift versions.
=> Set up the Swift version the extractor declares

.github/workflows/codeql.yml
Ensure we are regularly running code scanning using the latest CodeQL and remain up to date with the internal security scorecard, even if we have a period longer than a week with no pushes to the repo.
- [N/A] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [N/A] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.
=> Code scanning: Add scheduled trigger to workflow

lib/defaults.json, src/defaults.json
In order to have more fine-grained control the CLI version present in the toolcache, we will be downloading the most recent 2 versions of the CLI bundle to the toolcache and selecting a version (based on feature flag rollout of the most recent version) for the Action.  
The runner image script selects the bundle from the `defaults` file to determine which version of CodeQL to download. This change adds the bundle release prior to the most recent release under the field `priorBundleVersion` so that it is able to download both versions. We keep the `bundleVersion` field named the same to maintain backwards compatibility so that this change can be merged independently of the other changes in the Action.
The change also adds the CLI version for both the most recent release, and the prior …
=> Add CLI version field and prior release fields to `defaults` file

.github/update-release-branch.py, .github/workflows/post-release-mergeback.yml, .github/workflows/update-release-branch.yml
This change stops releasing CodeQL Action v1.  We should merge it after doing a last v1 release to incorporate #1481.  Commit-by-commit review recommended since I've done some drive by tech debt removal.
=> Remove v1 from the release process

CHANGELOG.md, lib/defaults.json, src/defaults.json
Update the default CodeQL bundle to `codeql-bundle-20230120`, which packages CodeQL CLI 2.12.1.
=> Bump default CodeQL version to 2.12.1

.github/prepare-test/action.yml
We've been seeing some tests fail recently due to the `gh release list` command failing.  Because Bash doesn't fail on error by default, those errors weren't manifesting themselves until a later step.  This PR adds `set -e` so the `prepare-test` Action fails straight away.  This makes it slightly quicker to triage the error and saves a bit of runner time.
=> Fail `prepare-test` early when `gh release list` fails

.github/workflows/__swift-autobuild.yml, pr-checks/checks/swift-autobuild.yml
There's a known issue that causes the Swift autobuilder to hang.  By setting a timeout, we'll fail earlier and we can rerun the check earlier.
=> Limit Swift autobuild runtime in PR check to 10 minutes

CONTRIBUTING.md
Now that we are no longer supporting v1, we should remove mention of it in our release documentation.
=> Remove v1 from release docs

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update default CodeQL bundle version to 2.12.3

.github/workflows/script/check-node-modules.sh, .github/workflows/script/update-node-modules.sh, .github/workflows/update-dependencies.yml
This is failing with a similar problem to #1544:
```
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/runner/.npm/_cacache/tmp/ded008dd
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/runner/.npm"
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2023-02-24T19_48_49_727Z-debug-0.log
Error: Process completed with exit code 243.
```
Port over the fix from https://github.com/github/codeql-action/pull/1544 and share code so these scripts don't get out of sync again.
=> Fix workflow to update dependencies

.github/dependabot.yml, .github/setup-swift/action.yml
Our Swift extractor is now using Swift v5.7.3, but our `setup-swift` version was pinned to a prior version that doesn't support v5.7.3, so our CI is failing.
This change bumps `setup-swift` to its most recent release commit SHA (https://github.com/swift-actions/setup-swift/releases/tag/v1.22.0).
It also adds a new entry to the `dependabot.yml` file because Dependabot should have bumped this version — `setup-swift` v1.22.0 was released two weeks ago and we run Dependabot checks weekly. Per the dependabot maintainers, the [filepath needed is the root of the repo](https://github.com/dependabot/dependabot-core/issues/5137#issuecomment-1441799333) (`/.github/workflows` is specially cased under `/`). 
We also add a comment reminding the next person who approves a Dependabot update to manually …
=> Bump `setup-swift` and re-configure dependabot

.github/codeql/codeql-config.yml
We added the support of `security-experimental` in https://github.com/github/codeql-action/pull/1519, but did not add `security-experimental` to the `codeql-config.yml` file then because we were waiting on a CLI v2.12.2 release to make it to the cached tools. Now that this is in, we can add the suite in to ensure it continues to work.
=> Add `security-experimental` to `codeql-config.yml`

.github/workflows/update-supported-enterprise-server-versions.yml, .github/workflows/update-supported-enterprise-server-versions/update.py
A classic GHES version which does not follow the current version numbering scheme was recently added to [`releases.json`](https://github.com/github/enterprise-releases/blob/master/releases.json), which broke the script we use to update the versions of GHES supported by the Action.
This PR ignores this version when performing the comparison.
Example Actions run: https://github.com/github/codeql-action/actions/runs/4448233726/jobs/7810782068
=> Ignore classic GHES version when updating supported versions 

tests/multi-language-repo/.github/codeql/custom-queries.yml
They have moved from `dsp-testing` to `codeql-testing`.
Internal refactoring, no user facing changes.
=> Use new location for external queries

.github/workflows/update-bundle.yml
This PR switches the update-bundle release trigger from `prereleased` to `published` because the former has been documented not to work.
From https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release:
> Note: The prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.
=> Fix pre-release trigger for update-bundle action

.github/actions/update-bundle/index.ts
The `bundleVersion` is the whole tag, we don't want to remove the `codeql-bundle-` prefix.
Commit-by-commit review recommended since we autoformat the update bundle Action in the second commit.
=> Fix the `bundleVersion` field set by the automated bundle update PR

CHANGELOG.md, README.md
Also, use a better link in the readme.
=> Add link to changenote for custom config

src/sarif-schema-2.1.0.json
`($i)` is not valid for javascript regexes.
Fixes https://github.com/github/codeql-action/issues/1671
=> Fix broken regex

CHANGELOG.md
Push back the first bundle released using a semantic version number to 2.13.4 now that we're skipping 2.13.2.
=> Push back semver CodeQL bundles

.github/workflows/__multi-language-autodetect.yml, pr-checks/checks/multi-language-autodetect.yml
We should check language autodetect for Ruby unconditionally. We can now move it into the step that checks all other languages; it was likely separated from other languages because of an experimental environment variable we needed to have set for Ruby before it was in GA.
=> Remove unnecessary conditional for Ruby autodetect

CONTRIBUTING.md, README.md
Make `CONTRIBUTING.md` more visible and fix the Node and `npm` versions.  As suggested in https://github.com/github/codeql-action/pull/1694.
=> Contributing documentation updates

.github/workflows/update-supported-enterprise-server-versions.yml, .github/workflows/update-supported-enterprise-server-versions/update.py
Wait a week to ensure the GHES version is definitely end of life, and open the PR using the `gh` CLI rather than a third-party Action.
=> Improve automation for updating supported versions of GHES

CHANGELOG.md
One of the changelog entries for 2.3.6 ended up incorrectly being associated with 2.3.4 due to a bad merge conflict resolution.  As a long term fix, we could store unreleased changelog entries in a separate directory and only edit `CHANGELOG.md` with automation.
=> Fix changelog for 2.3.6

CHANGELOG.md, node_modules/.package-lock.json, package-lock.json, package.json
Bump the version of the Action to 2.20.0. This ensures that users who received a Dependabot upgrade to [`cdcdbb5`](https://github.com/github/codeql-action/commit/cdcdbb579706841c47f7063dda365e292e5cad7a), which was mistakenly marked as Action version 2.13.4, continue to receive updates to the CodeQL Action.
- The CodeQL Action repository contains a series of tags `v*` corresponding to versions of the CodeQL Action. However it also contains a series of tags `codeql-bundle-*` that correspond to versions of the CodeQL Bundle, an artifact that contains the CodeQL CLI and the standard CodeQL libraries.
- In CodeQL CLI version 2.13.4, we changed the format of the CodeQL Bundle tag from a date, for example `codeql-bundle-20230613`, to a semantic version, for example `codeql-bundle-v2.13.4`. This …
=> Bump Action version to 2.20.0

python-setup/auto_install_packages.py
Recently released pipenv removed support for `--keep-outdated` flag (see https://github.com/pypa/pipenv/blob/main/CHANGELOG.rst#pipenv-202379-2023-07-09)
Local testing showed that installation was fine without this :+1:
=> python-setup: Fix pipenv (`--keep-outdated` deprecated)

.github/workflows/__config-export.yml, pr-checks/checks/config-export.yml
This was used to enable a feature flag, but the associated feature flag has now been removed and the functionality enabled for everyone.
=> Remove redundant environment variable from PR check

.github/actions/check-sarif/action.yml
`using: node12` Actions have already been running using Node 16 for some time, so this won't have any effect, but it is more correct and avoids warnings.
=> Run check-sarif Action using Node 16

.github/dependabot.yml
In https://github.com/github/codeql-action/pull/1774, I found I had to downgrade these dependencies to make things work.  This PR ignores them in the Dependabot config so they won't be included in our grouped updates.
=> Update Dependabot config to ignore incompatible updates

.github/actions/setup-swift/action.yml, .github/workflows/__export-file-baseline-information.yml, pr-checks/checks/export-file-baseline-information.yml
In default setup and the starter workflow, we don't setup Swift on macOS.  Therefore in our PR checks, let's do the same.  We continue setting up Swift on Linux, as we only run Swift on macOS in default setup and the starter workflow.
=> PR checks: Make Swift setup more consistent with default setup

.github/workflows/update-dependencies.yml
Improve the experience of using the updating dependencies workflow:
- Mark the PR as draft if we pushed a commit to update the dependencies.
- Add a comment asking the user to mark the PR as ready for review to trigger the checks.
=> Improve usability of update dependencies workflow

.github/workflows/update-dependencies.yml
This PR fixes the `unknown flag: --pr` error in "Update dependencies" workflow runs.
=> Remove --pr in update-dependencies.yml

.github/workflows/update-supported-enterprise-server-versions/update.py
The GHES versions automation looks up the GHES versions from an internal JSON file.  This contains a single version number from a previous numbering scheme, which we want to ignore as it is older than the 2.* and 3.* series.  Recently it was changed from 11.10.340 to 11.10, prompting the automation to open [a spurious update PR](https://github.com/github/codeql-action/pull/1878).
This PR updates the ignored version number to fix the automation.
=> Update ignored version number in GHES versions automation

init/action.yml
=> Improve description of codeql-action/init languages input

.github/workflows/__analyze-ref-input.yml, .github/workflows/__upload-ref-sha-input.yml, pr-checks/checks/analyze-ref-input.yml, pr-checks/checks/upload-ref-sha-input.yml
These checks aren't affected by the CLI version, so just run them with the default CLI to reduce CI load.  This lets us remove 42 jobs from our PR checks.
=> Remove 42 CI jobs by only running `ref` and `sha` input checks against a single CLI version

.github/workflows/codeql.yml
I'd like to be able to trigger this workflow manually, rather than wait for its scheduled instance or open a PR.
=> Add `workflow_dispatch` manual trigger

CHANGELOG.md, README.md
Make the announcement in the [issue](https://github.com/github/codeql-action/issues/1959) visible via the Action changelog and the README.
=> Add announcement on Node 16 deprecation

.github/workflows/rebuild.yml
Reduce friction when applying suggestions or handling merge conflicts via the GitHub UI.  Previously we needed to go back into the developer environment and rebuild.  Now we can apply a label and have Actions do it for us.
=> Add workflow to rebuild the Action on a label

.github/workflows/debug-artifacts-failure.yml, .github/workflows/debug-artifacts.yml
Ensure that pythion 3.11 is used for older CLIs on windows.
Similar to https://github.com/github/codeql-action/pull/1928.
=> Fix failing workflows

lib/codeql.js, src/codeql.ts
Warn users of CodeQL v2.11.5 and earlier that the next minor release of the CodeQL Action will require CodeQL v2.11.6 or later.
=> Prepare for CodeQL v2.10.5 deprecation

CHANGELOG.md
I should follow my own instructions! :)
=> Add changelog note for CodeQL v2.10.5 deprecation

.github/workflows/post-release-mergeback.yml, CHANGELOG.md
This PR adds a short explanation of our approach to version numbering at the top of the changelog.
It also ensures any change to the opening text is handled in the mergeback scripting, by anchoring the insertion of the new section to the existing `##` heading rather than the previous hardcoded line number.
=> add note on versioning approach to changelog

.github/workflows/pr-checks.yml, CONTRIBUTING.md
In order to keep alignment of check names across all the maintained branches, we backport the matrix job to the `releases/v2` branch.
The check runs on node 16 and skips for the current version (node 20).
=> backport checks changes to v2 branch

.github/actions/release-branches/release-branches.py
Simply casts a string to an int 😸
=> Fix type error in `Update release branch` workflow

README.md
We can remove this bit now that v3 is released 😸
=> Remove Node 16 deprecation note

queries/required-action-input.ql, queries/undeclared-action-input.ql
These predicates will be removed as of the next CLI release.  Also remove `getEntrypoint()` in `queries/required-action-input.ql` since it is unused.
=> Internal queries: Replace deprecated predicates

README.md
This information is already included in the changelog, but let's surface it in the README to so that it's more visible.
=> Add a README section about supported versions

analyze/action.yml, upload-sarif/action.yml
In working w/ @aibaars, we think this is clearer and more accurately describes what happens/doesn't happen as applicable.
=> Clarify that ref inputs are ignored for forks

.github/workflows/__with-checkout-path.yml, pr-checks/checks/with-checkout-path.yml
These tests do not depend on the CodeQL version.
Also disable debug mode in checkout path tests.  This avoids uploading debug artifacts, which takes a while.
=>  Only run custom checkout path tests against a single CodeQL version 

.github/workflows/debug-artifacts-failure.yml, .github/workflows/debug-artifacts.yml
These checks take a while, and there's no specific reason to run them on MacOS in particular. We run them only on `ubuntu-latest` instead.
=> Stop running debug artifacts checks on MacOS

.github/update-release-branch.py
Most of the replaced content generated by this script are links (SHAs, users, PRs). In general, it's really helpful for non-boilerplate content to be easily recognizable, and links are a good way to do that. As branches come and go, it isn't practical to use links for that purpose, but it is possible to use backticks to call out the branch name.
With these changes, https://github.com/github/codeql-action/pull/2131#issue-2132405833 would have looked like this:
> Merging [c79c360](https://github.com/github/codeql-action/commit/c79c360e02b1d0dbe91a088f7cf6de2c9f8c85b9) into `releases/v3`.
> 
> Conductor for this PR is ....
> 
> Contains the following pull requests:
> 
> ...
> 
> Please do the following:
> 
> * [x]  Ensure the CHANGELOG displays the correct version and date.
> * [x]  Ensure …
=> Add backticks around branch in update-release-branch PR template

.github/workflows/rebuild.yml
This should reduce a common source of friction when we have two PRs in flight that touch the same file.
=> Teach rebuild Action how to resolve conflicts in lib

CONTRIBUTING.md
=> Update release documentation with `v3` instructions

README.md
=> Add permissions info to README

README.md
=> README: Fix a couple of typos

.github/workflows/debug-artifacts-failure.yml
The `ram: 1` trick won't work anymore with recent updates to the CLI, so we need to find an alternate way to fail the `analyze` step here.
=> Fail `analyze` step in PR check by passing an invalid option to `database finalize`

init/action.yml
The `packs` input to `init` is no longer experimental.
=> Remove "experimental" designation from `packs` input

.github/actions/check-codescanning-config/action.yml, .github/actions/query-filter-test/action.yml, init/action.yml
Documents the `tools:` input and its options for the various workflow files.
Companion PR to https://github.com/github/codeql-action/pull/2281
Fixes https://github.com/github/codeql-action/issues/1327
=> Add documentation for the `tools` option in the various workflow files

init/action.yml
The `autobuild` Action is no longer needed or recommended when a build mode is specified.
=> Update docs for `build-mode: autobuild`

.github/workflows/__multi-language-autodetect.yml, .github/workflows/__scaling-reserved-ram.yml, .github/workflows/__swift-custom-build.yml, .github/workflows/__unset-environment.yml, .github/workflows/debug-artifacts.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/checks/scaling-reserved-ram.yml, pr-checks/checks/swift-custom-build.yml, pr-checks/checks/unset-environment.yml
With the new Linux runner image rollout and CLI versions <= 2.17.3, all PR checks with Swift are failing. This PR disables those tests to unblock CI for now. When CLI version 2.17.4 makes it to `nightly-latest` and `latest`, we will re-enable these tests.
The failing PR checks that were previously running on both `ubuntu` and `macos` have been updated to only run on `macos` for now. The failing PR checks that were previously running on only `ubuntu` have also been updated to only run on `macos` for now, so that we are at least covering these checks on one operating system. 
Now that the debug artifacts check runs on `macos` instead of `ubuntu`, old versions of the CLI <2.15.1 are experiencing the known build tracer bug on ARM Macs, so those are disabled for now as well. We …
=> PR Checks: disable tests for Swift on Linux until CLI 2.17.4

.github/workflows/codeql.yml
The macOS 11 runner image is deprecated on Dotcom.
=> Remove macOS 11 check and add macOS 14

.github/workflows/__multi-language-autodetect.yml, .github/workflows/__scaling-reserved-ram.yml, .github/workflows/__swift-custom-build.yml, .github/workflows/__unset-environment.yml, .github/workflows/debug-artifacts.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/checks/scaling-reserved-ram.yml, pr-checks/checks/swift-custom-build.yml, pr-checks/checks/unset-environment.yml, pr-checks/sync.py
We often need to exclude specific combinations of CLI versions + operating systems. Previously there was no easy way to do this: we would run all CLI versions specified against all operating systems specified. This change adds the `excludeOsAndVersionCombination` parameter to do just that!
To test, I re-enabled Swift on Linux for CLI v >= 2.17.4, which remained as a to-do item after we disabled those checks in https://github.com/github/codeql-action/pull/2299. Note that `default`, `linked`, and `nightly-latest` are all now current enough to re-enable those. The new generator script allows us to exclude all older CLI versions on Linux. 
I'll update the required PR checks once this PR is approved ✅
=> PR check generator: add `excludeOsAndVersionCombination`

CHANGELOG.md
I just noticed that the changelog entry for https://github.com/github/codeql-action/pull/2368 is in the wrong section — this PR fixes that.  It's a common mistake with automatic merge resolution in that file — we should consider dropping unreleased changelog entries in a folder instead like we do for the CLI.
=> Fix changelog entry section

.github/workflows/pr-checks.yml
A common mistake is forgetting to compile the code. Ideally, this wouldn't be necessary, but in the meantime, this change gives a visible indication on the commit when the code hasn't been recompiled.
Caveat: we will run duplicate "Check JS" jobs for `push` and `pull_request` when the commit is part of a pull request.
=> Check compiled code on each push

CHANGELOG.md
=> Add swift+linux deprecation

.github/workflows/script/update-required-checks.sh
The "Check JS" job and "Unit Test" job are both in the same workflow.  On push, we run the "Check JS" job but skip the "Unit Test" run to save compute.  This results in a skipped (non-matrixed) "Unit Test" job.  This PR makes sure that that "Unit Test" job doesn't get included in the required checks for main and the release branches, which we maintain via a script.
=> Exclude push-only unit tests job from required PR checks script

README.md
The release candidate is [now out](https://github.blog/changelog/2024-08-07-the-github-enterprise-server-3-14-release-candidate-is-available/).
=> Add details of supported versions for GHES 3.14

README.md
Also add a note about GHES 3.11 supporting but not shipping with CodeQL Action v3.
=> Fix formatting issue with GHES compatibility table

.github/workflows/__go-tracing-autobuilder.yml, .github/workflows/__go-tracing-custom-build-steps.yml, .github/workflows/__go-tracing-legacy-workflow.yml, pr-checks/checks/go-tracing-autobuilder.yml, pr-checks/checks/go-tracing-custom-build-steps.yml, pr-checks/checks/go-tracing-legacy-workflow.yml
This PR updates the version of Go in the PR checks to 1.23. This purely affects the CI on this repository. If you have come here because of an issue with CodeQL and Go 1.23, please open an issue on https://github.com/github/codeql
=> Go: Bump Go version to 1.23 in tests

.github/actions/setup-swift/action.yml
=> Update setup-swift version

analyze/action.yml, upload-sarif/action.yml
This documentation is currently misleading as it implies you can use any token here. In reality, this Action calls API endpoints that only accept tokens from the GitHub Actions app, so you should basically never override it.
I believe all the other Actions in this repository will work with an arbitrary token if one needs to be provided for cross-repository access, but these two call the SARIF upload endpoint which requires an Actions token.
=> Fix incorrect documentation about the `token` input to the Actions.

.github/workflows/update-release-branch.yml
The script `.github/update-release-branch.py` uses the `git` command to push changes. Therefore we need to ensure that `git` authenticates with a token that has the `workflows` write permision.
This change restore the GitHub token used by the script to access the API and applies the `workflows` write permission to the token used by `git`.
=> Use generated token on checkout

.github/workflows/__go-custom-queries.yml, .github/workflows/__remote-config.yml, .github/workflows/__unset-environment.yml, pr-checks/checks/go-custom-queries.yml, pr-checks/checks/remote-config.yml, pr-checks/checks/unset-environment.yml
These features have stabilized so it isn't that helpful to test them against the full range of CLIs.  So let's speed up the PR checks and save some Actions minutes.
Overall, this PR removes 50 jobs, taking the total number down from 306 to 256.
=> Run some tests against only `latest` and `nightly-latest` CLIs

.github/workflows/rebuild.yml
Previously the rebuild workflow would not check in new files, since `git commit -a` only adds changes to tracked files.
=> CI: Check in new files when rebuilding

.github/workflows/pr-checks.yml
Dependabot does not have `security-events: write` permission.
See https://github.com/github/codeql-action/pull/2485
=> Avoid uploading eslint sarif for dependabot PR

CHANGELOG.md
Realized that we dropped mention of the early November timeframe for making the dependency upgrade behavior the default in the Action.
=> Add notice for dependency upgrade timeline

.github/dependabot.yml
See https://github.com/github/codeql-action/pull/2510 for reason why.
=> Exclupde `eslint-plugin-import` updates from dependabot

CHANGELOG.md
This went into the wrong place due to a semantic merge conflict.
=> Fix changelog note section

.github/workflows/debug-artifacts-failure.yml, .github/workflows/debug-artifacts-legacy.yml, .github/workflows/debug-artifacts.yml
We are planning to make the default behavior of the `CODEQL_ACTION_ARTIFACT_V4_UPGRADE` feature flag to be true. This change updates our debug artifact PR checks so that the relevant environment variable is set to `true`, and changes the `debug-artifacts-upgrade` test to `debug-artifacts-legacy` test.
=> PR Checks: update artifacts tests

.github/workflows/post-release-mergeback.yml, .github/workflows/script/prepare_changelog.py
Must make sure this release is not marked as `latest` or else it will interfere with the CLI bundle releases also included in this repo.
See https://cli.github.com/manual/gh_release_create
=> Create a GitHub release for each action release

.github/actions/prepare-test/action.yml
While working on a version of this for testing on runner images, I noticed some improvements to be made:
- the action now expects stable CLI version inputs as `stable-vX.Y.Z` rather than with dates. Our current PR checks already use this format but the documentation for the input needed to be updated.
- the nightly version format also should expect `nightly-YYYYMMDD` rather than with dashes
- the nightly bundle URL formatting has been corrected to remove the `manual` suffix — eg. the current nightly URLs look like: `https://github.com/dsp-testing/codeql-cli-nightlies/releases/download/codeql-bundle-20240823/codeql-bundle-linux64.tar.gz`. We haven't caught this because none of our PR checks use the dated nightly bundles.
- when the version is `linked` or `default` we return the appropriate …
=> PR checks: small fixups to `prepare-action`

.github/workflows/script/update-required-checks.sh
Dependabot does not upload eslint alerts, so the check is never created.
=> Remove ESLint from required checks

action.yml
This is required for the migration of the codeql-action to an immutable action.
We can delete this after the migration is done, or just keep it so people have an extra way to understand how to use the action.
- [n/a] Confirm this change is backwards compatible with existing workflows.
- [n/a] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [n/a] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.
=> Add the action stub

.github/actions/prepare-test/action.yml
Experimentally, gzip bundles extract faster than zstd bundles on Windows with our current setup, so this change speeds up the PR checks in addition to better matching the production environment.
We are also separately looking into whether we can speed up bundle installation on Windows.
=> Use gzip bundles in Windows PR checks

.github/workflows/__config-export.yml, .github/workflows/__diagnostics-export.yml, .github/workflows/__export-file-baseline-information.yml, .github/workflows/__job-run-uuid-sarif.yml, .github/workflows/__zstd-bundle-streaming.yml, .github/workflows/__zstd-bundle.yml, pr-checks/checks/config-export.yml, pr-checks/checks/diagnostics-export.yml, pr-checks/checks/export-file-baseline-information.yml, pr-checks/checks/job-run-uuid-sarif.yml, pr-checks/checks/zstd-bundle-streaming.yml, pr-checks/checks/zstd-bundle.yml
- Split from #2578 per https://github.com/github/codeql-action/pull/2578#issuecomment-2463427214
=> Upgrade workflows to `actions/upload-artifact@v4`

.github/workflows/post-release-mergeback.yml
We need to do this because using a default token will not recursively trigger a new workflow run.
The only way to test this is to merge to main and do a release.
=> Use an app token for triggering a release

.github/workflows/post-release-mergeback.yml
The `app-id` is only available in the `Automation` environment.
=> Adds an environment for creating releases

.github/workflows/__go-indirect-tracing-workaround-diagnostic.yml, .github/workflows/__go-indirect-tracing-workaround-no-file-program.yml, .github/workflows/__go-indirect-tracing-workaround.yml, .github/workflows/__go-tracing-autobuilder.yml, .github/workflows/__go-tracing-custom-build-steps.yml, .github/workflows/__go-tracing-legacy-workflow.yml, .github/workflows/__multi-language-autodetect.yml, .github/workflows/debug-artifacts.yml, CHANGELOG.md, README.md, lib/codeql.js, node_modules/.package-lock.json, package-lock.json, package.json, pr-checks/checks/go-indirect-tracing-workaround-diagnostic.yml, pr-checks/checks/go-indirect-tracing-workaround-no-file-program.yml, pr-checks/checks/go-indirect-tracing-workaround.yml, pr-checks/checks/multi-language-autodetect.yml, pr-checks/sync.py, src/codeql.ts
=> Bump the minimum supported version of CodeQL to 2.15.5

.github/workflows/pr-checks.yml, CONTRIBUTING.md
Now that we have deprecated v2, we no longer need to maintain compatibility with Node 16.
=> Remove Node 16 compilation PR check

.github/workflows/query-filters.yml
Related issue: https://github.com/github/codeql-core/issues/4779
This adds a minimal permissions block to `query-filters.yml`. The CI check seems to still pass.
=> Update workflow permissions

.github/codeql/codeql-actions-config.yml, .github/workflows/codeql.yml
This enables the new actions analysis queries for this repository.
=> Add actions analysis to code scanning

.github/workflows/__rubocop-multi-language.yml, pr-checks/checks/rubocop-multi-language.yml
=> Pin `ruby/setup-ruby` Action to v1.215.0

resolve-environment/action.yml, start-proxy/action.yml
Partially fixes https://github.com/github/codeql-action/security/code-scanning/1050. The `upload-sarif` token description is the most comprehensive so I've used it for `resolve-environment` and `start-proxy`.
=> Unify `token` description for `resolve-environment`, `start-proxy`, and `upload-sarif`

.github/actions/check-codescanning-config/action.yml, .github/actions/check-codescanning-config/index.ts
- Use environment variable for `EXPECTED_CONFIG_FILE_CONTENTS` to escape any injected input
- Use `$RUNNER_TEMP` rather than `${{ runner.temp }}` for good measure, even though `runner.temp` should not be user-controlled input anyway.
=> Fix code injection warnings in `check-codescanning-config` internal Action

.pre-commit-config.yaml, justfile
* pre-commit: move the linting check ahead of the compiling one, as a typescript lint can change the compiled javascript, so you can end up in a situation where the pre-commit check fails twice in a row, while now one run should always work
* just: add linting and make the default to run all
=> Do some just+pre-commit tweaking

justfile
This PR is adding some utility `just` instructions that I had in a local file that I was using, before we added the current one.
The changes here are merely for convenience/documentation of maintainers - they don't (normally) affect users.
=> build: sync some utility just instructions I had locally

.github/actions/prepare-test/action.yml, .github/actions/release-branches/action.yml
This PR moves a number of uses of `${{ inputs.foo_bar }}` into environment variables for the step in question.
=> move use of input variables into env vars

.github/workflows/codeql.yml
The `ubuntu-20.04` image has been deprecated and is now causing CI failures for e.g. #2869. This PR removes `ubuntu-20.04` from the workflow and instead adds the newer `ubuntu-24.04`.
=> Remove ubuntu-20.04 and add ubuntu-24.04

.github/dependabot.yml
This field will soon be ignored.  We could add the production shield as codeowner instead, but that might be noisy.  I think if it's a pain point, we create an automation to add a comment to the current production shield issue with any Dependabot PRs.
=> Dependabot: Remove deprecated `reviewers` config

.github/workflows/update-proxy-release.yml
This PR adds a new workflow which automates the creation of PRs that update which release is used by the `start-proxy` action to pull binaries of the `update-job-proxy` from. 
Previously, I manually created PRs [such as this one](https://github.com/github/codeql-action/pull/2869) for that. The new workflow here creates similar ones, [such as this example](https://github.com/github/codeql-action/pull/2944).
This PR currently contains a commit that adds a `push` trigger (limited to this branch) for testing, which should be removed before merging this PR.
=> Add workflow for updating release used by `start-proxy`

tests/multi-language-repo/.gitignore, tests/multi-language-repo/Package.swift, tests/multi-language-repo/Sources/main.swift
It seems like the `Package.swift` trying to reuse the source code of the xcode project is not buildable by Swift 5.8.1 (or 5.9.2 for what matters). This just generates an independent default executable package with `swift package init` (using swift 5.8.1).
=> Swift: recreate a default Swift package to fix test

CHANGELOG.md
This adds the changelog entry for the v3.28.20 release into the changelog on `main`.
=> Add changelog entry for v3.28.20 backport

.github/workflows/__autobuild-direct-tracing-with-working-dir.yml, .github/workflows/__autobuild-direct-tracing.yml, pr-checks/checks/autobuild-direct-tracing-with-working-dir.yml, pr-checks/checks/autobuild-direct-tracing.yml, pr-checks/sync.py
Gradle 9 is now the default version of Gradle on the GHA runners. This seems to cause failures because JDK 8 is the default and Gradle 9 requires JDK 17.
This PR adds a new `installJava` option to the `sync.py` script which behaves exactly the same as `installGo`, except for `setup-java`.
I have added `installJava: "true"` to the two workflows we have seen fail.
- Consider adding a [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) entry for …
=> Add workflow generator option for installing Java

lib/init-action.js, src/config-utils.test.ts, src/config-utils.ts
This problem was introduced in https://github.com/github/codeql-action/pull/3009 since `lstatSync` throws an exception by default if the filesystem object doesn't exist. 
We likely didn't come across this because it requires both of the following conditions to hold:
- There is no `.github/workflows` folder
- And there is no input to `languages`
- …
=> Fix `hasActionsWorkflows` throwing an exception if the workflows folder doesn't exist

lib/analyze-action.js, lib/init-action.js, lib/upload-lib.js, lib/upload-sarif-action.js, src/overlay-database-utils.test.ts, src/overlay-database-utils.ts
This PR adds automation ID to the overlay-base database cache key so that we properly distinguish different analyses in the same repo for the same language.
Since I am changing the cache key format, I also moved the CodeQL bundle version to the end of the cache restore key, in case we want to remove it from the restore key sometime in the future.
Note that I chose to leave `CACHE_VERSION` unchanged because the old and the new cache keys are sufficiently different that there should be no risk of confusion.
Changes in this PR has been validated in an internal test repository.
- **Low risk:** Changes are fully under feature flags, or have been fully tested and validated in pre-production environments and are highly …
=> Overlay: add automation ID to cache key

tests/multi-language-repo/.gitignore
Since I have C# extensions for VSCode installed, it likes to generate some files in the `multi-language-repo` folder when I have the `codeql-action` workspace open. This updates the `.gitignore` file to ignore those files.
=> Add C# artifacts to `.gitignore` for `multi-language-repo`

lib/analyze-action.js, lib/upload-lib.js, lib/upload-sarif-action.js, src/environment.ts, src/upload-lib.ts
This introduces a new internal environment variable flag (`CODEQL_ACTION_SARIF_DUMP_DIR`) that, when set to `true`, causes the SARIF file that will be uploaded to be dumped to the specified directory. The filename will be `upload.sarif` or `upload.quality.sarif` depending on the upload target.
- Confirm the …
=> Dump soon to be uploaded SARIF on request

lib/analyze-action.js, src/analyze.ts
We accidentally kept `dbAnalysisConfig` here when refactoring this into its own function, instead of `analysis`. This meant that the check never succeeded, unless `code-quality` was the only active analysis.
=> Fix `runInterpretResultsFor` using the wrong `AnalysisConfig` for Code Quality `category` fix

lib/start-proxy-action.js, src/start-proxy-action.ts
Fixes a bug with https://github.com/github/codeql-action/pull/3110, where we missed setting this header for `toolcache.downloadTool` that's needed to get the actual artifact, rather than the JSON metadata.
Better solution than #3119, since `browser_download_url` is intended for use by browsers.
- Confirm the …
=> Specify `Accept` header for `toolcache.downloadTool`

lib/analyze-action.js, lib/init-action.js, src/overlay-database-utils.ts, src/trap-caching.ts, src/util.test.ts, src/util.ts
The name `withTimeout()` gives the impression that it would limit the execution of the promise to the given time bound. But that is not the case: it is only the _waiting_ that is limited, and the promise would keep running beyond the time bound.
This PR renames `withTimeout()` to `waitForResultWithTimeLimit()` so that developers are more likely to understand the actual behavior of this function.
- Consider adding a …
=> Rename withTimeout() to waitForResultWithTimeLimit()

lib/analyze-action.js, lib/init-action.js, src/overlay-database-utils.ts
This PR changes overlay-base database download to pass the `segmentTimeoutInMs` option to `restoreCache()`, so that `restoreCache()` itself can properly abort slow downloads.
The `waitForResultWithTimeLimit()` wrapper around `restoreCache()` remains as a second line of defense, but with a higher 10-minute time limit, to guard against cache restore hangs outside segment downloads.
See linked issue for rationale and alternatives considered.
- Consider adding a …
=> Overlay: use restoreCache() timeout

.github/workflows/__upload-quality-sarif.yml, lib/upload-sarif-action.js, pr-checks/checks/upload-quality-sarif.yml, src/upload-sarif-action.ts, upload-sarif/action.yml
In https://github.com/github/codeql-action/pull/3064, we overlooked that `upload_lib.uploadFiles` is called in the `upload-sarif` Action, which will fail if it cannot find any SARIF files matching the predicate it is given.
For a Code Quality only analysis, there are no Code Scanning SARIF files and the call to `upload_lib.uploadFiles` therefore fails before the Code Quality SARIF file(s) can be uploaded.
This PR refactors the `upload-sarif` Action so that there's common code for Code Scanning and Code Quality to upload either one file or several matching files.
There are some optional, other changes in this PR as well, which I can remove if needed:
- ~The `UploadStatusReport` values for each SARIF upload are now combined for telemetry if both analysis kinds are enabled. Otherwise, we use …
=> Fix `upload-sarif` Action failing if there are no Code Scanning SARIF files

.github/workflows/script/update-required-checks.sh
Fix an error condition that could cause the set of required checks to be emptied.
=> CI: Improve safety of update required checks script

justfile
Some tests require the `--serial` flag to pass.
=> build: use --serial in 'just test_file'

.github/workflows/rollback-release.yml
To avoid the issue observed in https://github.com/github/codeql-action/actions/runs/18004376110/job/51221112307#step:7:35
=> Don't dry-run `rollback-release` workflow on release branches

.vscode/settings.json, CONTRIBUTING.md, justfile, lib/analyze-action.js, lib/autobuild-action.js, lib/init-action.js, lib/resolve-environment-action.js, lib/start-proxy-action.js, lib/upload-lib.js, lib/upload-sarif-action.js, package.json
A few minor bits bundled up:
- Adds a `npm run ava` command; which can be used to run tests based on a custom path.
- Updates `npm run test` to use that, with the existing `src/` path.
- Updates `CONTRIBUTING.md` to highlight `npm run ava`
- Updates the `justfile` to use `npm run ava`
- Filters transpiled files and `node_modules` from search results in VSCode
- Consider adding a [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) entry for this …
=> Add `npm run ava` command, update instructions, and exclude files from VSCode search

.github/workflows/__upload-quality-sarif.yml, lib/upload-sarif-action.js, pr-checks/checks/upload-quality-sarif.yml, src/upload-sarif-action.ts, src/upload-sarif.test.ts, src/upload-sarif.ts
This PR takes parts of #3157:
- Moves logic from `upload-sarif-action.ts` to `upload-sarif.ts`
- Adds unit test coverage for the functions in `upload-sarif.ts`
- Fixes `sarif-ids` output format to match documentation
- Throws a `ConfigurationError` if no SARIF files were uploaded, matching the behaviour of `upload-sarif` prior to https://github.com/github/codeql-action/pull/3123
This doesn't make any further changes to the actual upload logic beyond the hotfix we added in #3160. I am planning a follow-up PR to improve on that after having come up with an idea for a good approach over the weekend, but want to the tests, `sarif-ids` fix, and error for the case where no files were uploaded merged first.
- **Low risk:** …
=> Add tests for `upload-sarif`

lib/analyze-action.js, lib/autobuild-action.js, lib/init-action.js, lib/resolve-environment-action.js, lib/start-proxy-action.js, lib/upload-lib.js, lib/upload-sarif-action.js, package-lock.json, package.json, src/codeql.ts
Bulk onboardings sometimes trigger errors due to the CodeQL download being rate limited.  Treat these as configuration errors as onboardings should be spread over a longer period of time to avoid rate limiting.
- **Advanced setup** - Impacts users who have custom workflows.
- **Default setup** - Impacts users who use default setup.
- **Code Scanning** - Impacts Code Scanning (i.e. `analysis-kinds: code-scanning`).
- **Code Quality** - Impacts Code Quality (i.e. `analysis-kinds: code-quality`).
- **GHES** - Impacts GitHub Enterprise …
=> Add configuration error for rate limited CodeQL download
