github/codeql-action

lib/config-utils.js, src/config-utils.ts
=> Fix parsing of path-ignore field

README.md, lib/config-utils.js, src/config-utils.ts
=> Merge changes from master into v1

.github/pull_request_template.md
Just noticed these on other PRs. We missed a couple of errors in this file.
=> Fix typos / errors in PR template

lib/finalize-db.js, lib/upload-lib.js, lib/upload-sarif.js, src/finalize-db.ts, src/upload-lib.ts, src/upload-sarif.ts
- ~https://github.com/Anthophila/test-electron/actions/runs/93132106~ :heavy_check_mark: 
- https://github.com/Anthophila/test-electron/actions/runs/93143541 :heavy_check_mark:
- ~https://github.com/Anthophila/test-electron/actions/runs/93132108~ :heavy_check_mark: 
- https://github.com/Anthophila/test-electron/actions/runs/93143542 :heavy_check_mark:
=> Report status as failure if upload fails in the finalize or upload action

.github/workflows/integration-testing.yml
=> Disable auto-detect language test on macos

README.md
QL was moved from `semmle/ql` to `github/codeql`.
=> Update CodeQL link in README

lib/analysis-paths.js, src/analysis-paths.ts
Changes `&&` to `||` to fix a logic error.
=> Fix the login in the isInterpretedLanguage method

.vscode/settings.json
=> Configure VSCode to ignore transpiled JavaScript

.github/update-release-branch.py
=> Update release branch base

.github/workflows/codeql.yml
=> Use v2 of checkout action

python-setup/auto_install_packages.py, python-setup/install_tools.sh
As we discussed, this adds support for installing packages through `setup.py`.
=> Update Python scripts for "Python deps setup"

README.md
This template proposes a time which is our peak load for Actions, would this time work better for our customers? Fixes https://github.com/github/codeql-action/issues/258
=> Change time in template

.github/workflows/python-deps.yml, lib/defaults.json, src/defaults.json
=> Use codeql 20201028

lib/defaults.json, src/defaults.json
=> Update default CodeQL bundle version

queries/import-action-entrypoint.ql
=> fix: small typo in import-action-entrypoint.ql

lib/defaults.json, src/defaults.json
=> Update the default bundle to `codeql-bundle-20201127`.

.github/workflows/integration-testing.yml
We should be testing using autobuild with Go as well as a manual build command, just in case.
=> Test Go autobuild

.github/workflows/integration-testing.yml, .github/workflows/pr-checks.yml, .github/workflows/script/check-js.sh, .github/workflows/script/check-node-modules.sh
Fixes #182.
I actually thought while doing this that we could just merge these two workflow files, I am not sure that we are getting any benefit from them being separate are we?
=> Gate execution of expensive tests on JS being up to date

.github/workflows/update-release-branch.yml
=> Don't run update release branch workflow on forks.

python-setup/install_tools.sh
This should fix the CI failures on #411. I can also cherry-pick this to the `v1` branch if we want it there too.
=> Fix the Pip download URL.

lib/defaults.json, src/defaults.json
=> Update CodeQL bundle to 20210503 / 2.5.4

.github/pull_request_template.md, CHANGELOG.md, node_modules/.package-lock.json, package-lock.json, package.json
Adds an empty changelog file and a reminder to update it when opening 
pull requests.
Also, adds a 1.0.0 version number in the package.json, which is what
we will use for version numbering.
=> Add a changelog

.gitattributes, CHANGELOG.md, README.md
=> Add the first changelog entry

.github/workflows/pr-checks.yml
=> Allow  to be run on workflow_dispatch

CHANGELOG.md
Forgot to follow my own advice before merging https://github.com/github/codeql-action/pull/631.
=> Changelog: Add note for CodeQL 2.5.9

.github/workflows/codeql.yml, .github/workflows/pr-checks.yml, CONTRIBUTING.md
=> Add brief instructions on creating a release

README.md
=> fix indentation error on README.md

lib/util.js, src/util.ts
=> Fix typo in docstring

README.md
=> README: Minor formatting edits

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update CodeQL bundle to 20210907 / 2.6.1

.github/workflows/update-release-branch.yml
The action will be released roughly every two weeks along
with the CodeQL CLI release process.
=> Remove scheduled releases

CHANGELOG.md, lib/defaults.json, src/defaults.json
PR for testing the new release. Do not merge yet.
=> Update default CodeQL version to 2.7.6

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update default CodeQL version to 2.8.0

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update bundle version to 2.8.1

.github/workflows/update-supported-enterprise-server-versions.yml, CONTRIBUTING.md
Some instructions on how to update required checks. I hope we can fully automate this soon, and these instructions will help.
=> Add some instructions on how to regenerate required checks

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update default CodeQL bundle version to 2.8.3

node_modules/.package-lock.json, node_modules/array-uniq/index.js, node_modules/array-uniq/license, node_modules/array-uniq/package.json, node_modules/array-uniq/readme.md, node_modules/github-linguist/node_modules/array-union/index.js, node_modules/github-linguist/node_modules/array-union/license, node_modules/github-linguist/node_modules/array-union/package.json, node_modules/github-linguist/node_modules/array-union/readme.md, package-lock.json
Looks like some dependencies were somehow missing. I'm still unclear quite how this happened, probably a change in one of the packages we depend on, or our Node version. Anyway, let's add them in to get our CI working again.
=> Fix issue with dependencies

CODEOWNERS
=> Add codeql-python as CODEOWNERS

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update codeql to 2.9.1

CHANGELOG.md, lib/defaults.json, src/defaults.json
Part of the 2.9.4 release process.
=> Update default CodeQL version to 2.9.4

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update default CodeQL version to 2.10.0

CHANGELOG.md, lib/defaults.json, src/defaults.json
- [N/A] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
=> Update default CodeQL version to 2.10.2

CHANGELOG.md, lib/defaults.json, python-setup/install_tools.ps1, python-setup/install_tools.sh, src/defaults.json
Part of the 2.10.4 release process.
=> Bump CodeQL version to 2.10.4

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Update default CodeQL version to 2.11.0

.github/workflows/script/update-required-checks.sh
Avoid requiring test-setup-python-scripts checks.
=> Update the checks script

CHANGELOG.md, lib/defaults.json, src/defaults.json
This version has the fix applied
=> Update bundle for 2.11.1

CHANGELOG.md, lib/defaults.json, src/defaults.json
Part of the 2.11.2 release process.
=> Bump default CodeQL version to 2.11.2

CHANGELOG.md
=> Add ATM 0.4.0 to changelog

README.md
=> Add Ruby to README

README.md
To make it easy for users to go to website for more info.
=> docs: add direct link to website

CHANGELOG.md, lib/defaults.json, src/defaults.json
=> Bump default CodeQL version to 2.12.2

.github/workflows/script/check-node-modules.sh
=> Clean the npm cache before running install

CHANGELOG.md
=> Add link to releases page in changelog

.github/actions/prepare-test/action.yml, .github/workflows/__test-local-codeql.yml, pr-checks/checks/test-local-codeql.yml
This PR speeds up our checks a bit by using platform specific bundles.
=> Use platform specific bundles in PR checks

.github/workflows/update-dependencies.yml
See [this failing run](https://github.com/github/codeql-action/actions/runs/6188628307/job/16801036002) for example.
=> Add GitHub token to update dependencies workflow

.github/workflows/script/update-required-checks.sh
This runs on `main` and is not relevant to PRs.
=> Exclude Dependabot updates workflow from required PR checks

.github/workflows/update-bundle.yml
Changed from `tools: latest` to `tools: linked` to reflect new usage.
=> Update PR description for bundle update PRs

CHANGELOG.md, lib/defaults.json, src/defaults.json
Reverts github/codeql-action#2312
=> Revert "Update default bundle to 2.17.4"

README.md
=> Add details of supported versions for GHES 3.13

.github/workflows/__swift-autobuild.yml
=> Fix workflow

.github/workflows/__swift-autobuild.yml, pr-checks/checks/swift-autobuild.yml
This brings it in line with recommended setups.
=>  Add build mode to Swift autobuild PR check

.github/workflows/script/update-required-checks.sh
This is a more robust approach to #2409.
=> Required checks script: Ignore skipped jobs

.github/workflows/__export-file-baseline-information.yml, pr-checks/checks/export-file-baseline-information.yml
Only set up Swift on macOS, since we only support Swift analysis on macOS.
=> Fix export file baseline test

.github/workflows/post-release-mergeback.yml
=> Add extra permission to mergeback workflow

package-lock.json, package.json
Supersedes https://github.com/github/codeql-action/pull/2797
=> Minimally remove micromatch

.github/workflows/update-bundle.yml
- **High risk:** Changes are not fully under feature flags, have limited visibility and/or cannot be tested outside of production.
=> Fix update-bundle workflow

CHANGELOG.md
=> Add retroactive changelog note for #3054

.github/pull_request_template.md
=> Add a reminder to the PR template that this is a public repo

lib/analyze-action.js, lib/autobuild-action.js, lib/init-action.js, lib/resolve-environment-action.js, lib/upload-lib.js, lib/upload-sarif-action.js, package-lock.json
Fixes https://github.com/github/codeql-action/security/dependabot/68 
- **High risk:** Changes are not fully under feature flags, have limited visibility and/or cannot be tested outside of production.
=> Update vulnerable dependency brace-expansion
